title: Guía Básica de Ordenadores
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://candelaaottero.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "https://static.guiainfantil.com/pictures/1015-dibujo-de-un-ordenador-para-colorear.jpg"
